OBJS = scanner.cmo parser.cmo tests.cmo runtest.cmo

runtests : $(OBJS)
	ocamlc -o runtests $(OBJS)

scanner.ml : scanner.mll
	ocamllex scanner.mll

parser.ml parser.mli : parser.mly
	ocamlyacc parser.mly

%.cmo : %.ml
	ocamlc -c $<

%.cmi : %.mli
	ocamlc -c $<


.PHONY : clean
clean :
	rm -rf *.cmo *.cmi runtests parser.mli parser.ml scanner.ml

# generated by ocamldep *.ml *.mli
tests-correct.cmo: scanner.cmo parser.cmi ast.cmi
tests-correct.cmx: scanner.cmx parser.cmx ast.cmi
tests.cmo: scanner.cmo parser.cmi ast.cmi tests.cmi
tests.cmx: scanner.cmx parser.cmx ast.cmi tests.cmi
parser.cmo: ast.cmi parser.cmi
parser.cmx: ast.cmi parser.cmi
runtest.cmo: tests.cmi
runtest.cmx: tests.cmx
scanner.cmo: parser.cmi
scanner.cmx: parser.cmx
ast.cmi:
tests.cmi: ast.cmi
parser.cmi: ast.cmi